### ISSUE TITLE
Find a solution to resue the typography in the mobile

### ISSUE THREAD

**Issue by amaljosea** [athulp8457/mira-amm-web#156]
Currently we are using media queries and overriding.

**Comment by amaljosea** [comment]
https://www.loom.com/share/c06ac91983864015b44c35e37a2a47d2?from_recorder=1&focus_title=1

**Comment by ap8457** [comment]
@amaljosea
Basically, we want separate typography to be applied for desktop and mobile?

**Comment by amaljosea** [comment]
Yes, mainly to solve this issue: https://github.com/athulp8457/mira-amm-web/pull/146#discussion_r2023419337

Some research: https://chatgpt.com/share/67e412fe-e008-800e-b00a-8099b1ec0f5c

**Comment by ap8457** [comment]
**Requirement** : Don't want to use tailwind. But requires similar behavior.

Current method :
Apply global class to component. Apply custom styles where required using media queries.

option 1: If we have a global rule.
(Say, all mc-type-xxxl In desktop should have "font-size: 22px;" for mobile. Or. all mc-type-l should be mc-type-m in mobile or something like that)
then we can apply the required changes in globals.css with media queries

Option 2 :
Install tailwind and solve our use-cases. Remaining code - leave as it is for now and can be slowly converted to tailwind later.
Why can't we go with this?

Option 3 :
use hooks. eg:  <div className={isMobile ? "text-sb" : "text-sm"}>
Not very clean. I don't recommend.

Option 4: 
something like this <div className="mobile:text-sb desktop:text-sm"}>

See if this is okay :
Got it! You need a **clean CSS-only solution** where you can apply different classes for desktop and mobile dynamically while keeping your existing `globals.css` intact.  

### **Solution: Use Space-Separated Classes with Media Queries**
You can define **modifier classes** in `globals.css` and apply them alongside your existing classes.

#### **Step 1: Define Modifier Classes in `globals.css`**
```css
/* Default (Desktop) styles */
.classA {
  font-size: 16px; /* Example */
}

.classB {
  font-size: 14px;
}

.classC {
  font-size: 18px;
}

.classD {
  font-size: 20px;
}

/* Mobile-specific overrides */
@media (max-width: 1024px) {
  .mobile-classB {
    font-size: 14px;
  }

  .mobile-classC {
    font-size: 16px;
  }

  .mobile-classD {
    font-size: 12px;
  }
}
```

---

#### **Step 2: Apply Classes in JSX**
Instead of using `mobile:text-sb desktop:text-sm`, simply apply a **default class** and a **mobile override class**:
```jsx
<div className="classA mobile-classB">Your Content</div>
<div className="classA mobile-classC">Another Content</div>
<div className="classA mobile-classD">Different Content</div>
```

---

### **Why This Works?**
- ✅ **No JS required**  
- ✅ **Keeps existing `globals.css` styles intact**  
- ✅ **Allows flexibility** (you can use `mobile-classB`, `mobile-classC`, etc., as needed)  
- ✅ **Readable and easy to maintain**  

Would this approach work for you? 🚀
